### ISSUE TITLE
latest is not up-to-date with codecov

### ISSUE THREAD

**Issue by phil-davis** [drone-plugins/drone-codecov#16]
In ownCloud, codecov reports stopped processing at the end of last week. I emailed to codecov support about it.

------------------------------

Since last weekend the codecov reporting has been consistently failing
in ownCloud repos. The CI says that it uploaded the codecov and gives a
link to the codecov site. But that link always says "There was an error
processing coverage reports." No codecov report is posted back to the
GitHub PR, and the GitHub CI status does not update.

e.g. GitHub PR https://github.com/owncloud/brute_force_protection/pull/90

CI in drone:
https://drone.owncloud.com/owncloud/brute_force_protection/960/5/5

--------

    -> Pinging Codecov
    -> Uploading
    -> View reports at
https://codecov.io/github/owncloud/brute_force_protection/commit/bf745876c2784a3bd1c34d2dd636d98dbebb9d1c

--------

And at that link it says "There was an error processing coverage reports."

Another example:

https://github.com/owncloud/core/pull/37415

CI in drone: https://drone.owncloud.com/owncloud/core/24945/24/10

View reports at
https://codecov.io/github/owncloud/core/commit/e4cf200f14b297fe4fddbfd528d65ae3a417f9bb

And that link has "There was an error processing coverage reports."

"something happened" (tm) maybe last Friday 15 May? Before that we were
getting codecov OK.

------------------------------

The reply:

------------------------------

Codecov recently did some fundamental storage changes on its backend in an effort to greatly improve the reliability of our underlying storage systems. As a result the X-Amz-Acl: public-read header is no longer needed, and may result in 400 errors if used.

Can you please update to the latest version of the uploader you are using and try again please?

------------------------------

So I switched CI to use `latest` docker:

------------------------------

Our CI uses https://hub.docker.com/r/plugins/codecov
https://github.com/drone-plugins/drone-codecov
It currently specifies plugins/codecov:2
That docker image is 2 years old.
I changed to plugins/codecov:latest
e.g. PR https://github.com/owncloud/brute_force_protection/pull/124
And the drone codecov pipeline step gives output https://drone.owncloud.com/owncloud/brute_force_protection/963/6/6
See attached file.

But I did get a codecov result back to GitHub - https://github.com/owncloud/brute_force_protection/pull/124#issuecomment-630940779 - good stuff.

The log does not look ideal - lines like "find: unrecognized: -execdir", and repeated upload attempts until it finally succeeds. Is that "normal"?
Or does https://hub.docker.com/r/plugins/codecov need something newer again?

------------------------------

The drone output is:
```
latest: Pulling from plugins/codecov
Digest: sha256:1f29a52ee88ba1c50306904df5913d090e3a54fd4a9f6fe4e3eaf8f5f957a424
Status: Downloaded newer image for plugins/codecov:latest
$ /bin/codecov -K -C 91c814c9209839cff9d861d20c55d5727ada5391 -B master -P 124 -b 963 -Z -s 'tests/output/clover.xml'

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-8a28df4


==> Drone CI detected.
    project root: .
--> token set from env
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
==> Running gcov in . (disable via -X gcov)
find: unrecognized: -execdir
BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.

Usage: find [-HL] [PATH]... [OPTIONS] [ACTIONS]

Search for files and perform actions on them.
First failed action stops processing of current file.
Defaults: PATH is current directory, action is '-print'

	-L,-follow	Follow symlinks
	-H		...on command line only
	-xdev		Don't descend directories on other filesystems
	-maxdepth N	Descend at most N levels. -maxdepth 0 applies
			actions to command line arguments only
	-mindepth N	Don't act on first N levels
	-depth		Act on directory *after* traversing it

Actions:
	( ACTIONS )	Group actions for -o / -a
	! ACT		Invert ACT's success/failure
	ACT1 [-a] ACT2	If ACT1 fails, stop, else do ACT2
	ACT1 -o ACT2	If ACT1 succeeds, stop, else do ACT2
			Note: -a has higher priority than -o
	-name PATTERN	Match file name (w/o directory name) to PATTERN
	-iname PATTERN	Case insensitive -name
	-path PATTERN	Match path to PATTERN
	-ipath PATTERN	Case insensitive -path
	-regex PATTERN	Match path to regex PATTERN
	-type X		File type is X (one of: f,d,l,b,c,s,p)
	-perm MASK	At least one mask bit (+MASK), all bits (-MASK),
			or exactly MASK bits are set in file's mode
	-mtime DAYS	mtime is greater than (+N), less than (-N),
			or exactly N days in the past
	-mmin MINS	mtime is greater than (+N), less than (-N),
			or exactly N minutes in the past
	-newer FILE	mtime is more recent than FILE's
	-inum N		File has inode number N
	-user NAME/ID	File is owned by given user
	-group NAME/ID	File is owned by given group
	-size N[bck]	File size is N (c:bytes,k:kbytes,b:512 bytes(def.))
			+/-N: file size is bigger/smaller than N
	-links N	Number of links is greater than (+N), less than (-N),
			or exactly N
	-prune		If current file is directory, don't descend into it
If none of the following actions is specified, -print is assumed
	-print		Print file name
	-print0		Print file name, NUL terminated
	-exec CMD ARG ;	Run CMD with all instances of {} replaced by
			file name. Fails if CMD exits with nonzero
	-exec CMD ARG + Run CMD with {} replaced by list of file names
	-delete		Delete current file/directory. Turns on -depth option
==> Python coveragepy not found
==> Searching for coverage reports in:
    + tests/output/clover.xml
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
    + tests/output/clover.xml bytes=18581
==> Appending adjustments
    http://docs.codecov.io/docs/fixing-reports
    + Found adjustments
==> Gzipping contents
==> Uploading reports
    url: https://codecov.io
    query: branch=master&commit=91c814c9209839cff9d861d20c55d5727ada5391&build=963&build_url=https%3A%2F%2Fdrone.owncloud.com%2Fowncloud%2Fbrute_force_protection%2F963&name=&tag=&slug=owncloud%2Fbrute_force_protection&service=drone.io&flags=&pr=124&job=
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-8a28df4&token=******&branch=master&commit=91c814c9209839cff9d861d20c55d5727ada5391&build=963&build_url=https%3A%2F%2Fdrone.owncloud.com%2Fowncloud%2Fbrute_force_protection%2F963&name=&tag=&slug=owncloud%2Fbrute_force_protection&service=drone.io&flags=&pr=124&job=
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-8a28df4&token=******&branch=master&commit=91c814c9209839cff9d861d20c55d5727ada5391&build=963&build_url=https%3A%2F%2Fdrone.owncloud.com%2Fowncloud%2Fbrute_force_protection%2F963&name=&tag=&slug=owncloud%2Fbrute_force_protection&service=drone.io&flags=&pr=124&job=
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-8a28df4&token=******&branch=master&commit=91c814c9209839cff9d861d20c55d5727ada5391&build=963&build_url=https%3A%2F%2Fdrone.owncloud.com%2Fowncloud%2Fbrute_force_protection%2F963&name=&tag=&slug=owncloud%2Fbrute_force_protection&service=drone.io&flags=&pr=124&job=
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-8a28df4&token=******&branch=master&commit=91c814c9209839cff9d861d20c55d5727ada5391&build=963&build_url=https%3A%2F%2Fdrone.owncloud.com%2Fowncloud%2Fbrute_force_protection%2F963&name=&tag=&slug=owncloud%2Fbrute_force_protection&service=drone.io&flags=&pr=124&job=
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Uploading to Codecov
    HTTP 200
https://codecov.io/github/owncloud/brute_force_protection/commit/91c814c9209839cff9d861d20c55d5727ada5391
```

codecov support responded:

------------------------------

My guess is https://hub.docker.com/r/plugins/codecov needs to be updated. It's not managed by Codecov, from your output it does not appear to be wrapping the latest version of the bash uploader.
​
You may want to try using the bash uploader directly, if possible.

------------------------------

What needs to be updated in this `plugins/codecov` docker image?

**Comment by tboerger** [comment]
The plugin is using the official bash script from codecov, but it haven't been updated for for some time. There errors look like it's not really compatible to the builtin tools of alpine linux.

**Comment by tboerger** [comment]
I have restarted the last build to fetch the latest shell script from codecov, please report if the error still applies to the latest tag.

**Comment by phil-davis** [comment]
seems to be working - thanks
