### ISSUE TITLE
find: unrecognized: -execdir

### ISSUE THREAD

**Issue by danmx** [drone-plugins/drone-codecov#17]
Current version of `find` doesn't support `-execdir` flag which is used in `codecov` bash script:
https://github.com/danmx/codecov-bash/blob/49bb153/codecov#L1081-L1083

**Comment by tboerger** [comment]
This is something Codecov got to fix, the plugin is just using the official Bash script.

**Comment by danmx** [comment]
@tboerger yes but the shell of your base image (`busybox`) doesn't support it and it works elsewhere. Also it only happens when you use `codecov.yml` config file

**Comment by thomasrockhu** [comment]
This was patched in the Codecov bash script https://github.com/codecov/codecov-bash/commit/fe0c473257c372daf1324bd92028c5623d1421ec#diff-45b1150df0237fb1cb2a238a2d04554e

**Comment by danmx** [comment]
then it would be a good idea to pin the version of the bash script instead of pulling latest: https://github.com/drone-plugins/drone-codecov/blob/931dc80/docker/Dockerfile.linux.amd64#L9

**Comment by tboerger** [comment]
We are using the official source to download the shell script, there haven't been any notice that this won't work with busybox or anything else.

**Comment by danmx** [comment]
I was trying to use `codecov.yml` configuration file in my repo and it broke the plugin. Maybe you just need to release a newer version. Last version of this plugin is from 2018 and the fix is from April 2020.

**Comment by thomasrockhu** [comment]
@danmx can you post the `codecov.yml` file here or preferably in our [community boards](https://community.codecov.io)

**Comment by tboerger** [comment]
The latest version of the image had been rebuilt, so it should be solved, if not please report it back here and I will do a deeper investigation.
