### ISSUE TITLE
Security issue in codecov bash uploader

### ISSUE THREAD

**Issue by xoxys** [drone-plugins/drone-codecov#18]
There is a critical security issue in the codecov bah uploader also used by this plugin. I highly recommend rebuilding the docker image to get the latest fixed version. For more details see https://about.codecov.io/security-update/

**Comment by ScOut3R** [comment]
By the looks of it the docker image was built 9 months ago while the tampering of the upload script started to happen this January. This means that the severely outdated docker image wasn't affected. Having said that an update would be nice. :)
