### ISSUE TITLE
Report adjustments are missing

### ISSUE THREAD

**Issue by DeepDiver1975** [drone-plugins/drone-codecov#3]
The codecov bash script is performing some report adjustment related to the path - see https://github.com/codecov/codecov-bash/blob/15cdf48a5c270730a650f853b26869304b2cc379/codecov#L1283-L1433

Without these adjustments the paths are displayed wrong in codecov itself.

**Comment by tboerger** [comment]
After merging #6 and #8 I will tag a new release, than it should work fine again.

**Comment by tboerger** [comment]
Fixed with #6 and #8

**Comment by DeepDiver1975** [comment]
> Fixed with #6 and #8

THX
