### ISSUE TITLE
Is it really the right way to reimplement the script?

### ISSUE THREAD

**Issue by DeepDiver1975** [drone-plugins/drone-codecov#4]
I honestly question if this approach is the right one.

The bash script (the official supported tool by codecov itself) holds many options and features and reimplementing will require some time.

Furthermore the script is under constant development and I fear that this plugin will by nature just be outdated.

Why not just reuse the bash script?

The original plugin we used (https://github.com/robertstettner/drone-codecov/blob/master/entrypoint.sh#L65) was just doing that and it worked - at least I have not seen any issues.

THX

**Comment by tboerger** [comment]
I have implemented this plugin in go mostly because of the portability.

Currently we don't have agents for arm or arm64 running, so it's not possible to build this plugin with a bash requirement.

If I reintroduce the shell script I have to drop the support for other architectures :(.

**Comment by tboerger** [comment]
For outdated plugin architecture, this plugin is built on a stable api, so this api will keep working even if the shell script gets extended.

**Comment by DeepDiver1975** [comment]
We could argue that building the logic within the bash script was a wrong decision by codecov in the first place - but never the less we have to live with this.

The bash script cannot work on arm?

**Comment by tboerger** [comment]
It works on arm, but it requires an native arm agent to build the docker image, the go version just gets cross built.

**Comment by tboerger** [comment]
After merging #6 and #8 I will tag a new release, than it should work fine again.

**Comment by tboerger** [comment]
Fixed with #6 and #8
