### ISSUE TITLE
'the docs' link in readme seems incorrect

### ISSUE THREAD

**Issue by butonic** [drone-plugins/drone-codecov#5]
Wanted to take a look, but http://plugins.drone.io/drone-plugins/drone-codecov/ just gives a list of plugins. In e 403 response ... something seems broken there?

**Comment by tboerger** [comment]
It's not wrong, I just forgot to create the PR to the docs repo for adding this page :(

**Comment by tboerger** [comment]
The docs are already published, just forgot to close this issue.
